# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: liveness.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "liveness.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eliveness.proto\x12\x08liveness"]\n\x0fLivenessRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0creference_id\x18\x02 \x01(\t\x12\x0b\n\x03jti\x18\x03 \x01(\t\x12\x13\n\x0binstruction\x18\x04 \x01(\t"C\n\x10LivenessResponse\x12\r\n\x05match\x18\x01 \x01(\x08\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2W\n\x0fLivenessService\x12\x44\n\x0b\x44\x65tectImage\x12\x19.liveness.LivenessRequest\x1a\x1a.liveness.LivenessResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "liveness_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LIVENESSREQUEST"]._serialized_start = 28
    _globals["_LIVENESSREQUEST"]._serialized_end = 121
    _globals["_LIVENESSRESPONSE"]._serialized_start = 123
    _globals["_LIVENESSRESPONSE"]._serialized_end = 190
    _globals["_LIVENESSSERVICE"]._serialized_start = 192
    _globals["_LIVENESSSERVICE"]._serialized_end = 279
# @@protoc_insertion_point(module_scope)
